-- 코드를 입력하세요
WITH TOTAL AS (
    SELECT JULY.FLAVOR, JULY.TOTAL_ORDER + IFNULL(FIRST_HALF.TOTAL_ORDER,0) TOTAL
    FROM JULY
    LEFT JOIN FIRST_HALF USING(SHIPMENT_ID)
) , FLAVOR_TABLE AS (
    SELECT  FLAVOR,
            SUM(TOTAL) TOTAL_ORDER
    FROM TOTAL
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
)

SELECT FLAVOR
FROM FLAVOR_TABLE LIMIT 3



